name: Run E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build App
        env:
          HOST: ${{ secrets.HOST }}
          ALL_ENVS: ${{ secrets.ALL_ENVS }}
        run: |
          if [ -z "$HOST" ]; then
            echo "HOST undefined. Building localapp..."
            npm run build &&
            npm start && npm run test:e2e
          else
            npm run test:e2e
          fi
